{
  name: "Nightly build",
  on: {
    push: {
      branches: [ "debug-nightly-build" ]
    },
  },
  jobs: {
    publish: {
      runs-on: "ubuntu-latest",
      steps: [
        { uses: "actions/checkout@v2" },
        {
          name: "Set up node 12",
          uses: "actions/setup-node@v1",
          with: {
            registry-url: "https://registry.npmjs.com",
            node-version: "12"
          }
        },
        { run: "yarn" },
        {
          run: "yarn publish --no-git-tag-version --new-version `node scripts/getNightlyVersion.js` --tag nightly",
          env: {
            NODE_AUTH_TOKEN: "${{ secrets.NPM_PUBLISH_TOKEN }}"
          }
        },
      ]
    }
  }
}

